//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemploCRUDEntityframework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblArchivos
    {
        public int Id { get; set; }
        public string NombreArchivo { get; set; }
        public byte[] Archivo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Size { get; set; }
    }
}
